config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'players#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :clubs
  resource :users
  resources :hello_app
  namespace :admin do
    resources :update_matches
    resources :clubs do
      collection do
        resources :update_players, controller: 'clubs/update_players'
      end
    end
  end
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/club.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: clubs
#
#  id         :integer          not null, primary key
#  name       :string           not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class Club < ApplicationRecord
  has_many :player
end

app/models/file_update.rb
class FileUpdate < ApplicationRecord

end

app/models/match.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: matches
#
#  id         :integer          not null, primary key
#  date       :date
#  event      :string           not null
#  handicap   :integer          default(0)
#  komi       :decimal(2, 1)    not null
#  result     :string
#  round      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  black_id   :integer
#  white_id   :integer
#
# Indexes
#
#  index_matches_on_black_id  (black_id)
#  index_matches_on_white_id  (white_id)
#
# Foreign Keys
#
#  black_id  (black_id => players.id)
#  white_id  (white_id => players.id)
#
class Match < ApplicationRecord
  belongs_to :white, class_name: 'Player', foreign_key: "white_id"
  belongs_to :black, class_name: 'Player', foreign_key: "black_id"
end

app/models/player.rb
# frozen_string_literal: true

# == Schema Information
#
# Table name: players
#
#  id           :integer          not null, primary key
#  birthyear    :integer          not null
#  display_name :string           not null
#  is_male      :integer          default(1), not null
#  name         :string           not null
#  rating       :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  club_id      :integer          not null
#
# Indexes
#
#  index_players_on_club_id             (club_id)
#  index_players_on_name_and_birthyear  (name,birthyear) UNIQUE
#
# Foreign Keys
#
#  club_id  (club_id => clubs.id)
#
class Player < ApplicationRecord
  belongs_to :club
  has_many :matches, ->(player) {
    unscope(:where).where(white: player).or(where(black: player))
  }

  def find_for_club(club_id)
    Player.where(club_id: club_id).all
  end

  def is_active
    (matches.size > 0) && (matches.maximum(:date) >= (Date.today - 365*4))
  end
end

app/models/tournament.rb
# == Schema Information
#
# Table name: tournaments
#
#  id         :integer          not null, primary key
#  end_date   :integer
#  name       :string           not null
#  start_date :integer
#
class Tournament < ApplicationRecord

end

app/models/update_club_players.rb
# == Schema Information
#
# Table name: update_from_files
#
#  id         :integer          not null, primary key
#  data       :string           not null
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class UpdateClubPlayers < UpdateFromFile
  def process_file
    players = PlayersParser.new.call file.download
    club_id = JSON.parse(data)["club_id"]
    players.each do |item|
      normalize_name = item[:name].mb_chars.unicode_normalize(:nfkd).gsub(/[^\x00-\x7F]/n,'').downcase.to_s
      birthyear = item[:birthyear]
      player = Player.find_by(name: normalize_name, birthyear: birthyear)
      if (!player)
        Player.create(name: normalize_name, birthyear: birthyear, club_id: club_id, display_name: item[:name])
      end
    end
  end
end

app/models/update_from_file.rb
# == Schema Information
#
# Table name: update_from_files
#
#  id         :integer          not null, primary key
#  data       :string           not null
#  type       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
class UpdateFromFile < ApplicationRecord
  after_create_commit :process_file
  has_one_attached :file

end

app/models/update_matches.rb
#  date       :date
#  event      :string           not null
#  handicap   :integer          default(0)
#  komi       :decimal(2, 1)    not null
#  result     :string
#  round      :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  black_id   :integer
#  white_id   :integer

class UpdateMatches < UpdateFromFile
    def process_file
      matches = MatchesParser.new.call file.download
      matches.each do |item|
        normalize_black_name = item[:black_name].mb_chars.unicode_normalize(:nfkd).gsub(/[^\x00-\x7F]/n,'').downcase.to_s
        normalize_white_name = item[:white_name].mb_chars.unicode_normalize(:nfkd).gsub(/[^\x00-\x7F]/n,'').downcase.to_s
        black_id = player.find_by(name: normalize_black_name).id 
        white_id = player.find_by(name: normalize_white_name).id
        result = item[:result]
        komi = decimal(item[:komi]) 
        handicap = integer(item[:handicap])
        date = date.parse item[:date]
        event = item[:event]
        round = item[:round]
        matches.create(date: date, event: event, handicap: handicap, komi: komi, result: result, round: round,
        black_id: black_id, white_id: white_id)
      end
    end
  end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/clubs/update_players_controller.rb
class Admin::Clubs::UpdatePlayersController < ApplicationController
  def new
    @update = UpdateFromFile.new
  end

  def create
    club_id = allowed_params[:club_id]
    allowed_params.delete(:club_id)
    update = UpdateClubPlayers.new(allowed_params)
    update.data = JSON.generate({club_id: club_id})
    update.save!
    redirect_to admin_update_players_path
  end

  def index
    @update_from_files = UpdateFromFile.all
  end

  private

  def allowed_params
    @allowed_params ||= params.require(:update_from_file).permit(:file, :club_id)
  end
end

app/controllers/admin/update_matches_controller.rb
class Admin::UpdateMatchesController < ApplicationController
    def new
        @update = UpdateMatches.new
    end

    def create
        update = UpdateMatches.new(allowed_params)
        update.data = JSON.generate({})
        update.save!
        redirect_to admin_update_matches_path
      end
    
    def index
        @update_matches = UpdateMatches.all
      end
    
    private

    def allowed_params
        @allowed_params ||= params.require(:update_matches).permit(:file)
    end
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/clubs_controller.rb
class ClubsController < ApplicationController
  def index
    @clubs = Club.all
  end

  def show
    id = params.require(:id)
    @players = Player.where(club_id: id).all
    @club = Club.find(id)
  end
end

app/controllers/hello_app_controller.rb
class HelloAppController < ApplicationController
    def index 
        @name = 'Thai'
    end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  def index
    @men = Player.where(is_male: 1).order(rating: :desc).all.filter{ |player| player.is_active }
    @women = Player.where(is_male: 0).order(rating: :desc).all.filter{ |player| player.is_active }
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/clubs_helper.rb
module ClubsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/clubs/update_players/index.html.slim
= @update_from_files.size
table
  - @update_from_files.each do |record|
    tr
      td = record.file.filename
      td = link_to "Download", rails_blob_url(record.file, disposition: "attachment")

app/views/admin/clubs/update_players/new.html.slim
= form_with model: @update, url:admin_update_players_path  do |f|
  = f.file_field :file
  = f.select :club_id, Club.all.map { |c| [c.name, c.id] }
  = f.submit

app/views/admin/update_matches/new.html.slim
= form_with model: @update, url:admin_update_matches_path  do |f|
  = f.file_field :file
  = f.submit

app/views/clubs/index.html.slim
table#clubs
  - for club in @clubs
    tr
      td.name
        = link_to club.name, club_path(id: club.id)

app/views/clubs/show.html.slim
= @club.name
table#players
  - for player in @players
    tr
      td = player.display_name

app/views/hello_app/index.html.slim
= @name
= 1 + 1
- 

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | VietnamGoRatings
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
  body
    - if notice
      |  <p class="
      a[href=""]
      | alert alert-success">
      = notice
    - if alert
      p.alert.alert-danger
        = alert
    = yield

app/views/players/index.html.slim
h1.container.mx-auto.title
  | Vietnam Go Ratings

.container.mx-auto
  .grid.grid-cols-1.md:grid-cols-2
    table.fixed-size.mx-auto
      thead
        tr
          td Nam
      tbody
        - @men.each_with_index do |player, index|
          tr
            td = index + 1
            td = player.display_name
            td = player.rating ? player.rating : "-"
    table.fixed-size.mx-auto
      thead
        tr
          td Nu
      tbody
        - @women.each_with_index do |player, index|
          tr
            td = index + 1
            td = player.display_name
            td = (player.rating != nil) ? player.rating: "-"

app/views/users/show.html.slim
p.navbar-text.float-right
  - if user_signed_in?
    |  Logged in as
    strong
      = current_user.email
    | .
    = link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link'
    |  |
    = link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'
  - else
    = link_to "Sign up", new_user_registration_path, :class => 'navbar-link'
    |  |
    = link_to "Login", new_user_session_path, :class => 'navbar-link'